### ISSUE TITLE
Trunk: no such file or directory

### ISSUE THREAD

**Issue by weykon** [yewstack/yew-playground#8]
```rust

use yew::prelude::*;

#[function_component]
fn App() -> Html {
    html! { "hello world" }
}

fn main() {
    yew::Renderer::<App>::new().render();
}

```
the result:
```
upstream connect error or disconnect/reset before headers. reset reason: remote reset
```

**Comment by hamza1311** [comment]
I added more logging and improved error handling. It seems that the trunk bin can't be located.
The lines
```
app_compiler: running command cmd=Command { std: "/usr/bin/trunk" "--config" "/app/Trunk.toml" "build", kill_on_drop: false }
app_compiler: running trunk failed e=Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
are logged by
https://github.com/yewstack/yew-playground/blob/e28b4f65f569457cde924b4d3e7f590c1e8be829/services/app-compiler/src/main.rs#L70
https://github.com/yewstack/yew-playground/blob/e28b4f65f569457cde924b4d3e7f590c1e8be829/services/app-compiler/src/main.rs#L75


I've updated the title to reflect the issue

**Comment by hamza1311** [comment]
This issue is fixed now
